# Generated by Django 3.2.4 on 2021-06-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='last_name',
        ),
    ]
