# Generated by Django 3.2.4 on 2021-06-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210628_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='age',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='education',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='mobile_number',
        ),
    ]
